In [1]:
import numpy as np
import pandas as pd
import json
import dill

In [2]:
model_name = "GEMM_EX"

In [23]:
train_set_original = pd.read_csv("data/{}_train_set_original.csv".format(model_name), dtype=np.object)
val_set_original = pd.read_csv("data/{}_val_set_original.csv".format(model_name), dtype=np.object)
test_set_original = pd.read_csv("data/{}_test_set_original.csv".format(model_name), dtype=np.object)

train_set = pd.read_csv("data/{}_train_set.csv".format(model_name))
val_set = pd.read_csv("data/{}_val_set.csv".format(model_name))
test_set = pd.read_csv("data/{}_test_set.csv".format(model_name))

In [5]:
with open("static/pipeline_gpa.pkl", "rb") as f:
    pipeline_gpa = dill.load(f)

with open("static/pipeline_rip.pkl", "rb") as f:
    pipeline_rip = dill.load(f)

## Load Vocabulary and Instantiate as dictionary : GPA

In [6]:
vocabulary_gpa = np.genfromtxt("static/vocabulary_gpa.csv", delimiter="\n", dtype=np.int64)
vocabulary_gpa

array([      -4096,          -1,           0, ...,    13058048,
       -1012228096,     -569308], dtype=int64)

In [7]:
vocabulary_gpa = {v:i for i, v in enumerate(vocabulary_gpa)}

In [8]:
dict(list(vocabulary_gpa.items())[:10])

{-4096: 0,
 -1: 1,
 0: 2,
 -1638400: 3,
 -1896448: 4,
 -864256: 5,
 -8192: 6,
 -4060: 7,
 13920476518: 8,
 -13920476522: 9}

## Demo : GPA

In [24]:
train_original_gpa_sample = train_set_original['gpa'].values[:30].astype(np.int64)

In [25]:
train_original_gpa_sample.astype

array(['14190604288.0', '14352732392.0', '14121463808.0', '14120734720.0',
       '14120828928.0', '19471331328.0', '14177644544.0', '14179282944.0',
       '17110061056.0', '17111699456.0', '14228705280.0', '14239969280.0',
       '14241607680.0', '14243504128.0', '19440017408.0', '18927992832.0',
       '18927996928.0', '18928001024.0', '18928005120.0', '18928009216.0',
       '18928029696.0', '18928037888.0', '14215737344.0', '18962931712.0',
       '14169337856.0', '14170099712.0', '14171131904.0', '14170525696.0',
       '14172348416.0', '14171140096.0'], dtype=object)

In [15]:
processed_train_sample = pipeline.transform(train_original_sample)
processed_train_sample

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 888,   0,   0,   0,   0,
         0,   0,  48])

In [16]:
# Delta
train_sample = train_original_sample[:-1] - train_original_sample[1:]
train_sample

array([-90096539952,      -528712,       -73032,      1315952,
            -160160,      -549096,       817016,      -248576,
           -1115480,      1044376,     -1382144,      -146992,
            1547488,      -558368,    -54420112,     54975104,
           -1362752,       433536,       516512,      -131600,
             433668,         6120,      -389321,      -901523,
              12160,    -19974760,     21278728,      -640432,
                -48], dtype=int64)

In [19]:
# Note that Irreversible predictions are returned as -1.
train_sample_inverse_transformed = pipeline.inverse_transform(processed_train_sample)
train_sample_inverse_transformed

array([  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
         -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1, 6120,
         -1,   -1,   -1,   -1,   -1,   -1,  -48], dtype=int64)

In [24]:
# Processed / Original Delta / Inverse_transformed (= restored from prediction)
processed_train_sample[21], train_sample[21], train_sample_inverse_transformed[21]

(888, 6120, 6120)

In [28]:
vocabulary[6120]

888

asd