In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)

In [3]:
dataset_name = "SEG_wavenet"

receptive_field = 257
quantization_channels = 16293

In [4]:
model = keras.models.load_model("model/model_1")

In [5]:
test_set_original = np.genfromtxt("data/{}_test_set.csv".format(dataset_name), delimiter="\n", dtype=np.int64)

In [6]:
test_y_set_original = test_set_original.copy()
test_y_set_original = test_y_set_original[receptive_field:]

In [7]:
test_y = test_y_set_original.reshape(-1, 1, 1)

In [8]:
#test_y = tf.one_hot(test_y, quantization_channels, axis=-1)
test_y = np.eye(quantization_channels)[test_y]
test_y = np.squeeze(test_y, axis=1)

In [9]:
test_x_set_original = test_set_original.copy()
test_x_set_original = test_x_set_original[:-1]

In [10]:
test_x = []

for i in range(len(test_x_set_original) - receptive_field + 1):
    test_x.append(test_x_set_original[i:i+receptive_field])

In [11]:
test_x = np.array(test_x)

In [12]:
test_x.shape, test_y.shape

((35322, 257), (35322, 1, 16293))

In [54]:
model.evaluate(test_x, test_y)

1104/1104 [==============================] - 19s 17ms/step - loss: 9.0165


9.016510963439941

In [14]:
result = model.predict_on_batch(test_x[:128])

In [17]:
tf.argmax(result, axis=-1)

<tf.Tensor: shape=(1, 128), dtype=int64, numpy=
array([[ 4927,     0,   171,     0,     0,  8384,     0,    64,     0,
            0,     0,   515,  3959,  2611,     0,  7268,    92, 12640,
         4126, 14557,  5349,     0,     0, 16266,  7997,     0,  6720,
         3025,     0,     0,  8358,  2264,  4722,    20,   106,    23,
           10,     0,   271,   324,   551,  2755,     0,  6338,     0,
            0,   368,  6883,     0,  4143,     1,     0, 12452,   421,
            0, 10486,     0,     0,   634,  4589,     1,     0,     0,
            0,     0,  3183,     0,  9936,     0,   312,     0,     0,
            0,     0, 15726,  7453,     0,     0,     0,     0, 13701,
            0,     0,     0,     0,   348,     0,  1159,   324,   235,
          324,   352,  2744,  4837,     0,     0,     0,     1,     0,
            0,    28,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 12422,  1280, 14399,     0,     0,     0,
            0,  7528,     0, 

In [18]:
test_y_set_original[:128]

array([   0,    0,    0,    0,    0,  250,  127,    0,  338,  185,  581,
        515,    0,    0,  205,    0,    0,  313,    0,    0,    0,    0,
         32,  421,  478,    0,    0,    0,    0,  464,  424, 4670,    0,
         20,    0,    0,    0,  192,  465,    0,  479,    0,  210,    0,
        249,  421,    0,  219,  436,    0,    0,  189,    0,    0,  201,
        192,    0,    0,  200,    0,  182,  378,  245,    0,    0,    0,
        334,  350,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,  216,    0,    0,    0,    0,  479,    0,  465,  109,
        402,  202,  324,  352,  219,    0,    0,    0,    0,    0, 2087,
        190,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        433,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int64)